In [1]:
!pip install torch torchvision

import torch

  Using cached https://files.pythonhosted.org/packages/85/5e/e91792f198bbc5a0d7d3055ad552bc4062942d27eaf75c3e2783cf64eae5/Pillow-5.4.1-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [2]:
x = torch.rand(2,5)
x

tensor([[0.3788, 0.6614, 0.9206, 0.6599, 0.4042],
        [0.6692, 0.7092, 0.0084, 0.4727, 0.9064]])

In [3]:
x.std()

tensor(0.2728)

In [6]:
x.data.std()

tensor(0.2728)

In [7]:
torch.ge(x,x.std())

tensor([[1, 1, 1, 1, 1],
        [1, 1, 0, 1, 1]], dtype=torch.uint8)

In [9]:
x.ge(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.uint8)